/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_udt_udt */

#ifndef _Included_com_udt_udt
#define _Included_com_udt_udt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_udt_udt
 * Method:    startup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_startup
  (JNIEnv *, jobject);

/*
 * Class:     com_udt_udt
 * Method:    cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_udt_udt
 * Method:    socket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_socket
  (JNIEnv *, jobject);

/*
 * Class:     com_udt_udt
 * Method:    connect
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_connect
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_udt_udt
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_udt_udt
 * Method:    send
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_udt_udt_send
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_udt_udt
 * Method:    recv
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_udt_udt_recv
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
